// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp1.Models;

#nullable disable

namespace WinFormsApp1.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WinFormsApp1.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Edinburgh, Scotland, UK",
                            Age = 58,
                            Brief = "British author, philanthropist, and film producer, best known for writing the Harry Potter fantasy series.",
                            Email = "jk@example.com",
                            Name = "J.K. Rowling",
                            Password = "password123",
                            Phone = "+44123456789",
                            userName = "jk_rowling"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gurnee, Illinois, USA",
                            Age = 71,
                            Brief = "American software engineer and author, also known as Uncle Bob. He is a co-author of the Agile Manifesto.",
                            Email = "bob@clean-coder.com",
                            Name = "Robert C. Martin",
                            Password = "securepass456",
                            Phone = "+19876543210",
                            userName = "uncle_bob"
                        });
                });

            modelBuilder.Entity("WinFormsApp1.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("authorId")
                        .HasColumnType("int");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("photoSourceString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("authorId");

                    b.HasIndex("categoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brief = "The first novel in the Harry Potter series.",
                            Description = "Harry Potter's life is miserable. His parents are dead and he's stuck with his heartless relatives. But his fortune changes when he receives a letter that tells him the truth about himself: he's a wizard. A mysterious visitor rescues him from his relatives and takes him to his new home, Hogwarts School of Witchcraft and Wizardry.",
                            Price = 250.50m,
                            PublishDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 100,
                            Title = "Harry Potter and the Philosopher's Stone",
                            authorId = 1,
                            categoryId = 1,
                            photoSourceString = "D:\\ITI\\data\\C#\\.Net\\LinQ-EF\\EntityFramworkDay2\\WinFormsApp1\\WinFormsApp1\\photos\\12744514_161090037606960_3174452805785756224_n.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Brief = "A Handbook of Agile Software Craftsmanship.",
                            Description = "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn't have to be that way. This book looks at the principles and best practices of writing clean, maintainable code.",
                            Price = 650.00m,
                            PublishDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 45,
                            Title = "Clean Code",
                            authorId = 2,
                            categoryId = 2,
                            photoSourceString = "D:\\ITI\\data\\C#\\.Net\\LinQ-EF\\EntityFramworkDay2\\WinFormsApp1\\WinFormsApp1\\photos\\cm-punk-tell-me-wallpaper-4k.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Brief = "A Code of Conduct for Professional Programmers.",
                            Description = "Programmers who endure and succeed amidst swirling uncertainty and nonstop pressure share a common attribute: They care about the practice of creating software. They treat it as a craft. They are professionals. In The Clean Coder: A Code of Conduct for Professional Programmers, legendary software expert Robert C. Martin introduces the disciplines, techniques, tools, and practices of true software craftsmanship.",
                            Price = 580.00m,
                            PublishDate = new DateTime(2011, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 20,
                            Title = "The Clean Coder",
                            authorId = 2,
                            categoryId = 2,
                            photoSourceString = "D:\\ITI\\data\\C#\\.Net\\LinQ-EF\\EntityFramworkDay2\\WinFormsApp1\\WinFormsApp1\\photos\\cm-punk-tell-me-wallpaper-4k.jpg"
                        });
                });

            modelBuilder.Entity("WinFormsApp1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fictional narrative works, including novels and short stories.",
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Books related to software, engineering, and modern tech advancements.",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Books documenting past events, civilizations, and historical figures.",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("WinFormsApp1.Models.Book", b =>
                {
                    b.HasOne("WinFormsApp1.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("authorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinFormsApp1.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WinFormsApp1.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("WinFormsApp1.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
